
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU1MjI0ODJ9.3Y7StLPUFL9vuxJ14xfsn5BUooy9lLVOim0vM9K6-oI

GET http://localhost:3000/actors

###
GET http://localhost:3000/actors/5

###
POST http://localhost:3000/actors
content-type: application/json
Authorization: Bearer {{jwt}}

{
  "first_name": "Ben ",
  "last_name": "Affleck",
  "known_for": "Batman",
  "movie_id" : 1
}

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Kevin Duncan",
  "email": "kevin@info.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "alex@info.com",
  "password": "password"
}

