
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU0NDk5MjN9.AkQgYYj9J2JrCTbwHXMtxtS4imA6lgyiv0Sxh8A0JvI

GET http://localhost:3000/actors

###
GET http://localhost:3000/actors/5
###

POST http://localhost:3000/actors
content-type: application/json

{
  "first_name": "Colin",
  "last_name": "Farrell",
  "known_for": "Phone Both",
  "movie_id" : 2
}

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Kevin Duncan",
  "email": "kevin@info.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "alex@info.com",
  "password": "password"
}

