GET http://localhost:3000/actor.json

###

GET http://localhost:3000/allactors.json

###

GET http://localhost:3000/query_single_actor?actor=Matt Demon

###

GET http://localhost:3000/url_single_actor/Matt Demon

###
POST http://localhost:3000/body_single_actor
content-type: application/json

{
  "actor" : "Matt Demon"
}

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Kevin Duncan",
  "email": "kevin@info.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "alex@info.com",
  "password": "password"
}

